// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avjbbpgrzcqgqzmslvym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2amJicGdyemNxZ3F6bXNsdnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDU4MTEsImV4cCI6MjA1OTc4MTgxMX0.MjkI1kafaYEKaVvAa3wXir-uSQJQNR4AJVbuvkIpA04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);